name: template
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  pretty_dio_logger: ^1.4.0
  talker_bloc_logger: ^4.8.0
  talker_flutter: ^4.8.0
  talker_dio_logger: ^4.8.0
  talker: ^4.8.0
  envied: ^1.1.1
  equatable: ^2.0.7
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  go_router: ^15.1.2
  easy_localization: ^3.0.7+1
  flex_color_scheme: ^8.2.0
  permission_handler: ^12.0.0+1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3
  injectable_generator: ^2.7.0
  envied_generator: ^1.1.1
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/translations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

